import { PrismaService } from '@/common/services/prisma.service';
import { UpdateUserInput } from './dto/update-user.input';
export declare class UsersService {
    private prisma;
    constructor(prisma: PrismaService);
    findAll(tenantId: string, skip?: number, take?: number): Promise<{
        email: string;
        firstName: string | null;
        lastName: string | null;
        phone: string | null;
        acquiredBy: string | null;
        acquiredVia: string | null;
        acquiredFrom: string | null;
        id: string;
        role: import(".prisma/client").$Enums.UserRole;
        emailVerified: Date | null;
        phoneVerified: Date | null;
        passwordHash: string | null;
        avatar: string | null;
        bio: string | null;
        tenantId: string;
        permissions: string[];
        metadata: import("@prisma/client/runtime/library").JsonValue | null;
        lastLoginAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    findOne(id: string): Promise<{
        ownedBusinesses: {
            email: string | null;
            phone: string | null;
            id: string;
            tenantId: string;
            metadata: import("@prisma/client/runtime/library").JsonValue | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            status: import(".prisma/client").$Enums.BusinessStatus;
            slug: string;
            tagline: string | null;
            description: string | null;
            logo: string | null;
            coverImage: string | null;
            whatsapp: string | null;
            website: string | null;
            address: string | null;
            city: string | null;
            state: string | null;
            country: string;
            postalCode: string | null;
            latitude: number | null;
            longitude: number | null;
            ownerId: string;
            verified: boolean;
            featured: boolean;
            plan: import(".prisma/client").$Enums.BusinessPlan;
            planExpiresAt: Date | null;
            metaTitle: string | null;
            metaDescription: string | null;
            keywords: string[];
            viewCount: number;
            clickCount: number;
            theme: import("@prisma/client/runtime/library").JsonValue | null;
        }[];
        subscriptions: {
            id: string;
            metadata: import("@prisma/client/runtime/library").JsonValue | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.SubscriptionStatus;
            businessId: string | null;
            userId: string;
            planId: string;
            currentPeriodStart: Date;
            currentPeriodEnd: Date;
            cancelAt: Date | null;
            canceledAt: Date | null;
            stripeSubscriptionId: string | null;
        }[];
    } & {
        email: string;
        firstName: string | null;
        lastName: string | null;
        phone: string | null;
        acquiredBy: string | null;
        acquiredVia: string | null;
        acquiredFrom: string | null;
        id: string;
        role: import(".prisma/client").$Enums.UserRole;
        emailVerified: Date | null;
        phoneVerified: Date | null;
        passwordHash: string | null;
        avatar: string | null;
        bio: string | null;
        tenantId: string;
        permissions: string[];
        metadata: import("@prisma/client/runtime/library").JsonValue | null;
        lastLoginAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    findByEmail(email: string): Promise<{
        email: string;
        firstName: string | null;
        lastName: string | null;
        phone: string | null;
        acquiredBy: string | null;
        acquiredVia: string | null;
        acquiredFrom: string | null;
        id: string;
        role: import(".prisma/client").$Enums.UserRole;
        emailVerified: Date | null;
        phoneVerified: Date | null;
        passwordHash: string | null;
        avatar: string | null;
        bio: string | null;
        tenantId: string;
        permissions: string[];
        metadata: import("@prisma/client/runtime/library").JsonValue | null;
        lastLoginAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    } | null>;
    update(id: string, input: UpdateUserInput): Promise<{
        email: string;
        firstName: string | null;
        lastName: string | null;
        phone: string | null;
        acquiredBy: string | null;
        acquiredVia: string | null;
        acquiredFrom: string | null;
        id: string;
        role: import(".prisma/client").$Enums.UserRole;
        emailVerified: Date | null;
        phoneVerified: Date | null;
        passwordHash: string | null;
        avatar: string | null;
        bio: string | null;
        tenantId: string;
        permissions: string[];
        metadata: import("@prisma/client/runtime/library").JsonValue | null;
        lastLoginAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    delete(id: string): Promise<{
        success: boolean;
    }>;
    getBusinesses(userId: string): Promise<{
        email: string | null;
        phone: string | null;
        id: string;
        tenantId: string;
        metadata: import("@prisma/client/runtime/library").JsonValue | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        status: import(".prisma/client").$Enums.BusinessStatus;
        slug: string;
        tagline: string | null;
        description: string | null;
        logo: string | null;
        coverImage: string | null;
        whatsapp: string | null;
        website: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        country: string;
        postalCode: string | null;
        latitude: number | null;
        longitude: number | null;
        ownerId: string;
        verified: boolean;
        featured: boolean;
        plan: import(".prisma/client").$Enums.BusinessPlan;
        planExpiresAt: Date | null;
        metaTitle: string | null;
        metaDescription: string | null;
        keywords: string[];
        viewCount: number;
        clickCount: number;
        theme: import("@prisma/client/runtime/library").JsonValue | null;
    }[]>;
    getListings(userId: string): Promise<{
        id: string;
        tenantId: string;
        metadata: import("@prisma/client/runtime/library").JsonValue;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ListingStatus;
        slug: string;
        description: string;
        city: string | null;
        state: string | null;
        country: string;
        latitude: number | null;
        longitude: number | null;
        featured: boolean;
        metaTitle: string | null;
        metaDescription: string | null;
        viewCount: number;
        clickCount: number;
        title: string;
        categoryId: string;
        businessId: string | null;
        userId: string;
        price: number | null;
        priceType: import(".prisma/client").$Enums.PriceType;
        currency: string;
        negotiable: boolean;
        location: string | null;
        shareCount: number;
        expiresAt: Date | null;
        publishedAt: Date | null;
    }[]>;
}
//# sourceMappingURL=users.service.d.ts.map