import { ListingsService } from './listings.service';
import { CreateListingInput, UpdateListingInput, ListingFilters } from './dto/listing.input';
export declare class ListingsResolver {
    private listingsService;
    constructor(listingsService: ListingsService);
    create(user: any, input: CreateListingInput): Promise<{
        id: string;
        tenantId: string;
        metadata: import("@prisma/client/runtime/library").JsonValue;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ListingStatus;
        slug: string;
        description: string;
        city: string | null;
        state: string | null;
        country: string;
        latitude: number | null;
        longitude: number | null;
        featured: boolean;
        metaTitle: string | null;
        metaDescription: string | null;
        viewCount: number;
        clickCount: number;
        title: string;
        categoryId: string;
        businessId: string | null;
        userId: string;
        price: number | null;
        priceType: import(".prisma/client").$Enums.PriceType;
        currency: string;
        negotiable: boolean;
        location: string | null;
        shareCount: number;
        expiresAt: Date | null;
        publishedAt: Date | null;
    }>;
    findAll(tenantId: string, filters?: ListingFilters): Promise<({
        user: {
            firstName: string | null;
            lastName: string | null;
            id: string;
            avatar: string | null;
        };
        business: {
            id: string;
            name: string;
            slug: string;
            logo: string | null;
        } | null;
        category: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            slug: string;
            description: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
            active: boolean;
            fieldsSchema: import("@prisma/client/runtime/library").JsonValue | null;
        };
        images: {
            id: string;
            createdAt: Date;
            listingId: string;
            url: string;
            order: number;
            caption: string | null;
        }[];
    } & {
        id: string;
        tenantId: string;
        metadata: import("@prisma/client/runtime/library").JsonValue;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ListingStatus;
        slug: string;
        description: string;
        city: string | null;
        state: string | null;
        country: string;
        latitude: number | null;
        longitude: number | null;
        featured: boolean;
        metaTitle: string | null;
        metaDescription: string | null;
        viewCount: number;
        clickCount: number;
        title: string;
        categoryId: string;
        businessId: string | null;
        userId: string;
        price: number | null;
        priceType: import(".prisma/client").$Enums.PriceType;
        currency: string;
        negotiable: boolean;
        location: string | null;
        shareCount: number;
        expiresAt: Date | null;
        publishedAt: Date | null;
    })[]>;
    findOne(slug: string): Promise<{
        user: {
            firstName: string | null;
            lastName: string | null;
            phone: string | null;
            id: string;
            avatar: string | null;
        };
        business: {
            email: string | null;
            phone: string | null;
            id: string;
            tenantId: string;
            metadata: import("@prisma/client/runtime/library").JsonValue | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            status: import(".prisma/client").$Enums.BusinessStatus;
            slug: string;
            tagline: string | null;
            description: string | null;
            logo: string | null;
            coverImage: string | null;
            whatsapp: string | null;
            website: string | null;
            address: string | null;
            city: string | null;
            state: string | null;
            country: string;
            postalCode: string | null;
            latitude: number | null;
            longitude: number | null;
            ownerId: string;
            verified: boolean;
            featured: boolean;
            plan: import(".prisma/client").$Enums.BusinessPlan;
            planExpiresAt: Date | null;
            metaTitle: string | null;
            metaDescription: string | null;
            keywords: string[];
            viewCount: number;
            clickCount: number;
            theme: import("@prisma/client/runtime/library").JsonValue | null;
        } | null;
        category: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            slug: string;
            description: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
            active: boolean;
            fieldsSchema: import("@prisma/client/runtime/library").JsonValue | null;
        };
        reviews: ({
            user: {
                firstName: string | null;
                lastName: string | null;
                id: string;
                avatar: string | null;
            };
        } & {
            comment: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.ReviewStatus;
            verified: boolean;
            title: string | null;
            businessId: string | null;
            userId: string;
            images: string[];
            listingId: string | null;
            rating: number;
            helpfulCount: number;
        })[];
        images: {
            id: string;
            createdAt: Date;
            listingId: string;
            url: string;
            order: number;
            caption: string | null;
        }[];
    } & {
        id: string;
        tenantId: string;
        metadata: import("@prisma/client/runtime/library").JsonValue;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ListingStatus;
        slug: string;
        description: string;
        city: string | null;
        state: string | null;
        country: string;
        latitude: number | null;
        longitude: number | null;
        featured: boolean;
        metaTitle: string | null;
        metaDescription: string | null;
        viewCount: number;
        clickCount: number;
        title: string;
        categoryId: string;
        businessId: string | null;
        userId: string;
        price: number | null;
        priceType: import(".prisma/client").$Enums.PriceType;
        currency: string;
        negotiable: boolean;
        location: string | null;
        shareCount: number;
        expiresAt: Date | null;
        publishedAt: Date | null;
    }>;
    update(user: any, id: string, input: UpdateListingInput): Promise<{
        id: string;
        tenantId: string;
        metadata: import("@prisma/client/runtime/library").JsonValue;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ListingStatus;
        slug: string;
        description: string;
        city: string | null;
        state: string | null;
        country: string;
        latitude: number | null;
        longitude: number | null;
        featured: boolean;
        metaTitle: string | null;
        metaDescription: string | null;
        viewCount: number;
        clickCount: number;
        title: string;
        categoryId: string;
        businessId: string | null;
        userId: string;
        price: number | null;
        priceType: import(".prisma/client").$Enums.PriceType;
        currency: string;
        negotiable: boolean;
        location: string | null;
        shareCount: number;
        expiresAt: Date | null;
        publishedAt: Date | null;
    }>;
    delete(user: any, id: string): Promise<{
        success: boolean;
    }>;
}
//# sourceMappingURL=listings.resolver.d.ts.map