import { BusinessService } from './business.service';
import { CreateBusinessInput, UpdateBusinessInput, UpdatePageConfigInput } from './dto/business.input';
export declare class BusinessResolver {
    private businessService;
    constructor(businessService: BusinessService);
    create(user: any, input: CreateBusinessInput): Promise<{
        email: string | null;
        phone: string | null;
        id: string;
        tenantId: string;
        metadata: import("@prisma/client/runtime/library").JsonValue | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        status: import(".prisma/client").$Enums.BusinessStatus;
        slug: string;
        tagline: string | null;
        description: string | null;
        logo: string | null;
        coverImage: string | null;
        whatsapp: string | null;
        website: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        country: string;
        postalCode: string | null;
        latitude: number | null;
        longitude: number | null;
        ownerId: string;
        verified: boolean;
        featured: boolean;
        plan: import(".prisma/client").$Enums.BusinessPlan;
        planExpiresAt: Date | null;
        metaTitle: string | null;
        metaDescription: string | null;
        keywords: string[];
        viewCount: number;
        clickCount: number;
        theme: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    findAll(tenantId: string, city?: string): Promise<({
        owner: {
            firstName: string | null;
            lastName: string | null;
            id: string;
            avatar: string | null;
        };
    } & {
        email: string | null;
        phone: string | null;
        id: string;
        tenantId: string;
        metadata: import("@prisma/client/runtime/library").JsonValue | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        status: import(".prisma/client").$Enums.BusinessStatus;
        slug: string;
        tagline: string | null;
        description: string | null;
        logo: string | null;
        coverImage: string | null;
        whatsapp: string | null;
        website: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        country: string;
        postalCode: string | null;
        latitude: number | null;
        longitude: number | null;
        ownerId: string;
        verified: boolean;
        featured: boolean;
        plan: import(".prisma/client").$Enums.BusinessPlan;
        planExpiresAt: Date | null;
        metaTitle: string | null;
        metaDescription: string | null;
        keywords: string[];
        viewCount: number;
        clickCount: number;
        theme: import("@prisma/client/runtime/library").JsonValue | null;
    })[]>;
    findOne(slug: string): Promise<{
        businessHours: {
            id: string;
            businessId: string;
            dayOfWeek: number;
            openTime: string;
            closeTime: string;
            closed: boolean;
        }[];
        listings: {
            id: string;
            tenantId: string;
            metadata: import("@prisma/client/runtime/library").JsonValue;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.ListingStatus;
            slug: string;
            description: string;
            city: string | null;
            state: string | null;
            country: string;
            latitude: number | null;
            longitude: number | null;
            featured: boolean;
            metaTitle: string | null;
            metaDescription: string | null;
            viewCount: number;
            clickCount: number;
            title: string;
            categoryId: string;
            businessId: string | null;
            userId: string;
            price: number | null;
            priceType: import(".prisma/client").$Enums.PriceType;
            currency: string;
            negotiable: boolean;
            location: string | null;
            shareCount: number;
            expiresAt: Date | null;
            publishedAt: Date | null;
        }[];
        reviews: {
            comment: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.ReviewStatus;
            verified: boolean;
            title: string | null;
            businessId: string | null;
            userId: string;
            images: string[];
            listingId: string | null;
            rating: number;
            helpfulCount: number;
        }[];
        owner: {
            email: string;
            firstName: string | null;
            lastName: string | null;
            phone: string | null;
            acquiredBy: string | null;
            acquiredVia: string | null;
            acquiredFrom: string | null;
            id: string;
            role: import(".prisma/client").$Enums.UserRole;
            emailVerified: Date | null;
            phoneVerified: Date | null;
            passwordHash: string | null;
            avatar: string | null;
            bio: string | null;
            tenantId: string;
            permissions: string[];
            metadata: import("@prisma/client/runtime/library").JsonValue | null;
            lastLoginAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        socialLinks: {
            id: string;
            createdAt: Date;
            businessId: string;
            platform: import(".prisma/client").$Enums.SocialPlatform;
            url: string;
            order: number;
        }[];
    } & {
        email: string | null;
        phone: string | null;
        id: string;
        tenantId: string;
        metadata: import("@prisma/client/runtime/library").JsonValue | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        status: import(".prisma/client").$Enums.BusinessStatus;
        slug: string;
        tagline: string | null;
        description: string | null;
        logo: string | null;
        coverImage: string | null;
        whatsapp: string | null;
        website: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        country: string;
        postalCode: string | null;
        latitude: number | null;
        longitude: number | null;
        ownerId: string;
        verified: boolean;
        featured: boolean;
        plan: import(".prisma/client").$Enums.BusinessPlan;
        planExpiresAt: Date | null;
        metaTitle: string | null;
        metaDescription: string | null;
        keywords: string[];
        viewCount: number;
        clickCount: number;
        theme: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    update(user: any, id: string, input: UpdateBusinessInput): Promise<{
        email: string | null;
        phone: string | null;
        id: string;
        tenantId: string;
        metadata: import("@prisma/client/runtime/library").JsonValue | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        status: import(".prisma/client").$Enums.BusinessStatus;
        slug: string;
        tagline: string | null;
        description: string | null;
        logo: string | null;
        coverImage: string | null;
        whatsapp: string | null;
        website: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        country: string;
        postalCode: string | null;
        latitude: number | null;
        longitude: number | null;
        ownerId: string;
        verified: boolean;
        featured: boolean;
        plan: import(".prisma/client").$Enums.BusinessPlan;
        planExpiresAt: Date | null;
        metaTitle: string | null;
        metaDescription: string | null;
        keywords: string[];
        viewCount: number;
        clickCount: number;
        theme: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    delete(user: any, id: string): Promise<{
        success: boolean;
    }>;
    updatePageConfig(user: any, input: UpdatePageConfigInput): Promise<{
        id: string;
        slug: string;
        theme: import("@prisma/client/runtime/library").JsonValue;
    }>;
    getPageConfig(businessId: string): Promise<{
        id: string;
        slug: string;
        theme: import("@prisma/client/runtime/library").JsonValue;
    }>;
}
//# sourceMappingURL=business.resolver.d.ts.map